const express = require("express");
const router = express.Router();
const adminInfo = require('../controllers/adminInfo')
const myindex = require('../controllers/indexPage.js')
const checklog = require('../controllers/checklog')
router.post("/permission/addGroup",adminInfo.addGroup)
router.post("/permission/addPermission",adminInfo.addPermission)
router.post("/permission/addMenu",adminInfo.addMenu)
router.get("/permission/admininfo",adminInfo.admininfo)
router.post("/permission/deleGroup",adminInfo.deleGroup)
router.post("/permission/delePermission",adminInfo.delePermission)
router.post("/permission/deleMenu",adminInfo.deleMenu)
router.post("/permission/deleUser",adminInfo.deleUser)
router.post("/permission/editManager",adminInfo.editManager)
router.post("/permission/editPermission",adminInfo.editPermission)
router.get("/permission/AllPermission",adminInfo.getAllPermission)
router.get("/permission/getAllMenu",adminInfo.getAllMenu)
router.get("/permission/getGroupInfo",adminInfo.getGroupInfo)
router.get("/permission/getManagerSingle",adminInfo.getManagerSingle)
router.get("/permission/getManagerUser",adminInfo.getManagerUser)
router.get("/permission/getPermissionList",adminInfo.getPermissionList)
router.get("/permission/getrolename",adminInfo.getrolename)
router.post("/permission/register",adminInfo.register)
router.get("/permission/selectPermission",adminInfo.selectPermission)
router.post("/permission/setpermission",adminInfo.setpermission)
router.post("/permission/setMenu",adminInfo.setMenu)
router.get("/permission/getzhuanyiList",adminInfo.getzhuanyiList)
router.get("/index/indexPage",myindex.indexPage)
router.post("/permission/zhuanyiziyuan",adminInfo.zhuanyiziyuan)
router.get("/checklog/checklog", checklog.checklog)
module.exports = router
